Hardware overview
goiabada/docs pull request #1
Opened 2019-04-17 18:27 UTC by Emethium

2019-04-17 19:55 UTC, alvadorn requested changes

2019-04-17 19:55 UTC, alvadorn commented on sections/overview/graphics.md
> +- The GBA refresh rate equates do 280,896 clock cycles per frame (the time it takes to display the entire video buffer) which equals to **59.73 Hz**, our maximum frame rate.
`equates to` ?

2019-04-18 02:31 UTC, alvadorn requested changes

2019-04-18 02:31 UTC, alvadorn commented on sections/overview/index.md
> +- The GBA architecture is similar to a PC in many ways. Both have one or more processors, RAM, a digital signal processor (DSP), a motherboar and a BIOS (Basic Input/Output System) that causes the ha
`a motherboard`

2019-04-18 13:22 UTC, Emethium commented on sections/overview/index.md
> +- The GBA architecture is similar to a PC in many ways. Both have one or more processors, RAM, a digital signal processor (DSP), a motherboar and a BIOS (Basic Input/Output System) that causes the ha
Typo fixed.

2019-04-18 13:23 UTC, Emethium commented on sections/overview/graphics.md
> +- The GBA refresh rate equates do 280,896 clock cycles per frame (the time it takes to display the entire video buffer) which equals to **59.73 Hz**, our maximum frame rate.
Yeah, another typo :sweat: Fixed!

2019-04-18 14:43 UTC, alvadorn approved these changes

2019-04-18 14:44 UTC, merged