I/O Mapping section
goiabada/docs pull request #4
Opened 2019-04-26 14:33 UTC by Emethium

And the missing Memory Gamepak session I forgot to include on #3 :sweat:

2019-04-26 20:38 UTC, pedrogryzinsky commented
@alvadorn

2019-04-27 01:23 UTC, alvadorn requested changes

2019-04-27 01:23 UTC, alvadorn commented on sections/memory/gamepak.md
> +- Although the 32 MB Game Pak memory space is mapped form **08000000h** onward, the 32 MB spaces beggining from **0A000000h** and **0C000000h** **are images** of the 32 MB space that starts at **0800
`is mapped from`?

2019-05-03 18:30 UTC, alvadorn approved these changes

2019-05-03 18:30 UTC, merged